[package]
name = "hello-rs"
version = "0.1.0"
edition = "2018"
license = "Apache-2.0"
description = "Hello World application"
repository = "https://github.com/barthelemystephane/hello_rs.git"

[dependencies]
